# Ordered by output of `jazzy — help config`
output: ProjectName_Docs
clean: true
xcodebuild_arguments:
- -workspace
- SuperMario.xcworkspace
- -scheme
- SuperMario
- CODE_SIGNING_ALLOWED = NO
author: Naz
module: SuperMario
module_version: 1.0
copyright: Copyright 2020
# exclude: AppDelegate.swift, SceneDelegate.swift
# Options : [apple | fullwidth | jony | DIRPATH]
# Which theme to use. Specify either ‘apple’ (default), one of the other built-in theme names, or the path to your mustache templates and other assets for a custom theme.Default: apple
theme: apple
