disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - line_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - SuperMario
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
force_try:
  severity: warning # explicitly
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50  
identifier_name:
  min_length: # only min_length
    error: 3 # only error
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
